<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ESI.NET" Version="2023.11.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EveMiningFleet.Entities\EveMiningFleet.Entities.csproj" />
  </ItemGroup>

</Project>
