<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UserSecretsId>dotnet-Cron-03587A38-7DCD-4AC3-BD4E-B364E794D037</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
    <StartupObject>Cron.Program</StartupObject>
  </PropertyGroup>
  

  <ItemGroup>
    <None Remove="Properties\launchSettings.json.sample" />
  </ItemGroup>

  <ItemGroup>
    <_WebToolingArtifacts Remove="Properties\PublishProfiles\launchSettings.json.sample" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="30.0.1" />
    <PackageReference Include="FluentScheduler" Version="5.5.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="3.1.32" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="3.1.32" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.19.5" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="log\" />
    <Folder Include="esidump\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EveMiningFleet.Entities\EveMiningFleet.Entities.csproj" />
    <ProjectReference Include="..\EveMiningFleet.Logic\EveMiningFleet.Logic.csproj" />
  </ItemGroup>

  <ProjectExtensions><VisualStudio><UserProperties properties_4launchsettings_1json__JsonSchema="" /></VisualStudio></ProjectExtensions>
</Project>
